HF_EMBED: mixedbread-ai/mxbai-embed-large-v1
COHERE_RERANKER: rerank-v3.5
LLM_MODEL_TYPE: OPENAI
PROMPT_DIR: prompts

# Local Storage Configuration
LOCAL_PERSIST_DIR: data/persist
LOCAL_TEMP_DIR: data/temp
LOCAL_CHAT_HISTORY_DIR: ../data/chat_history

OPENAI:
  CHAT:
    MODEL_NAME: gpt-4
    MAX_TOKENS: 1024
    TEMPERATURE: 0.3
    TOP_P: 0.9
    REQUEST_TIMEOUT: 180.0
    CONTEXT_WINDOW: 8192

OPENROUTER:
  CHAT:
    MODEL_NAME: meta-llama/llama-3-70b-instruct
    MAX_TOKENS: 2048
    TEMPERATURE: 0.6
    TOP_P: 0.7
    REQUEST_TIMEOUT: 180.0
    CONTEXT_WINDOW: 8192
  SMALL_MODEL:
    MODEL_NAME: meta-llama/llama-3-8b-instruct
    MAX_TOKENS: 512
    TEMPERATURE: 0.5
    TOP_P: 0.7
    REQUEST_TIMEOUT: 180.0
    CONTEXT_WINDOW: 8192

OLLAMA:
  CHAT:
    MODEL_NAME: llama3.1:8b
    CTX_LENGTH: 32768
    PREDICT_LENGTH: 4096
    TEMPERATURE: 0.7
    TOP_P: 0.7
    REQUEST_TIMEOUT: 600.0

ANTHROPIC:
  CHAT:
    MODEL_NAME: claude-3-opus-latest
    CTX_LENGTH: 32768
    PREDICT_LENGTH: 4096
    TEMPERATURE: 0.7
    TOP_P: 0.7
    REQUEST_TIMEOUT: 600.0

PDF_BASE_URL: https://rag-llm.s3.us-east-2.amazonaws.com/
S3_LOGS_BUCKET: altgan-logs
S3_CHAT_HISTORY: chat_logs
S3_PERSIST_BUCKET: altgan-persist
S3_PERSIST_DIR: /home/ubuntu

AWS_REGION: ap-south-1
SECRETS_MANAGER: rag_secrets
CLOUDWATCH_LOG_GROUP: ag-log-group
CLOUDWATCH_LOG_STREAM: ag-log-stream

QDRANT_ENABLE_HYBRID: True
FASTEMBED_SPARSE_MODEL: Qdrant/bm42-all-minilm-l6-v2-attentions
RAG_SIMILARITY_CUTOFF: 0.1
RAG_SIMILARITY_TOP_K: 20
RAG_RERANKED_TOP_N: 8
RAG_SIMILARITY_TOP_K_REPORT: 20
RAG_RERANKED_TOP_N_REPORT: 8
RAG_CITATION_CHUNK_SIZE: 1024
RAG_CITATION_CHUNK_OVERLAP: 32
RAG_STREAMING: True
RAG_SIMILARITY_CUTOFF_CHAT: 0.3
